### ISSUE TITLE
check prediction error of image classification

### ISSUE THREAD

**Issue by mkh48v** [mkh48v/omnis#166]
a prediction result of caltech101_densenet121.py is incorrect

maybe it is related with an loading process

**Comment by mkh48v** [comment]
or check predict method

**Comment by mkh48v** [comment]
@12rics 

a predict method works before save and load.

but after save and load a model, a prediction result was 'wrench'.

check initializer of Application and loading process

**Comment by 12rics** [comment]
works fine with basic cnn and tiny cnn. might be a problem with keras-imported models. class indices differ a lot in a same weight.

**Comment by 2013-11390** [comment]
cnn = DenseNet121(model_path='caltech101_densenet121.h5') 
didn't load class_indices and output_dictionary.

**Comment by 2013-11390** [comment]
In segmentation model, we have to save both model weights and class names files similar with classification.
I just put output dictionary in txt file for temporary method.
I check it works fine after save and load a model only in Resnet101 model.
We have to check other classification models and we have to change issue changing the save method.
