### ISSUE TITLE
Have to change saving method for output_dictionary in classification.

### ISSUE THREAD

**Issue by 2013-11390** [mkh48v/omnis#181]
Change the save method of application for saving trained weights and output dictionary in 1 file.
Now, we just saved model weights in h5 file and classes name in text. But we should provide 1 saved file for saving both things.
Now this is dirty code in fixClassification branch now.

**Comment by mkh48v** [comment]
consider saving class_indices only.(keras' default attribute of Model)
if we need a output dictionary, we can reverse class_indices loaded from h5 file.
