### ISSUE TITLE
fix save error of image classification

### ISSUE THREAD

**Issue by mkh48v** [mkh48v/omnis#239]
check

https://support.hdfgroup.org/HDF5/doc1.6/UG/11_Datatypes.html

and check error logs below

omnis\lib\image_proccessing\image_classification\saving_lib.py", line 98, in _serialize_model

keras\utils\io_utils.py", line 258, in __setitem__
   self.data.attrs[attr] = val
 File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
 File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

h5py\_hl\attrs.py", line 177, in create
   htype = h5t.py_create(original_dtype, logical=True)
 File "h5py\h5t.pyx", line 1630, in h5py.h5t.py_create
 File "h5py\h5t.pyx", line 1652, in h5py.h5t.py_create
 File "h5py\h5t.pyx", line 1707, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

maybe it's related with a typeerror

i suspect that this error is raised because of string type data saving code
(cast to a character or an array needed)

**Comment by 2013-11390** [comment]
This error occured because we try to put dict into h5 file directly

**Comment by mkh48v** [comment]
the bug is not fixed on windows platform.

reopen this issue
